name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build-latest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            amm0nite/mqtt2http:latest
          platforms: linux/amd64, linux/arm/v7, linux/arm64

  build-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push release
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            amm0nite/mqtt2http:${{ github.ref_name }}
          platforms: linux/amd64, linux/arm/v7, linux/arm64
